version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    container_name: marknotes-pg
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5656:5432'
    volumes:
      - './postgres/data:/var/lib/postgresql/data'